apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "common.metadata" (list $ (dict "labelsPath" "deployment.labels" "annotationsPath" "deployment.annotations")) | nindent 2 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "object.name" ( list $ "") }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "object.name" ( list $ "") }}
      containers:
        - name: {{ include "object.name" ( list $ "") }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
