apiVersion: apps/v1
kind: Deployment
metadata:
{{- include "common.metadata" . | nindent 2 }}
{{- if .Values.daemonsetAnnotations }}
  {{- toYaml .Values.daemonsetAnnotations | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
    {{- if .Values.podLabels }}
      {{- toYaml .Values.podLabels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
      {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "object.name" . }}
      containers:
        - name: {{ include "object.name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: app
              containerPort: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}