apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "probe-from-node.fullname" . }}
  labels:
    {{- include "probe-from-node.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "probe-from-node.fullname" . }}
  labels:
    {{- include "probe-from-node.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "probe-from-node.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "probe-from-node.fullname" . }}
  apiGroup: rbac.authorization.k8s.io