apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "common.metadata" (list $ (dict)) | nindent 2 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "object.name" ( list $ "") }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "object.name" ( list $ "" ) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "object.name" ( list $ "" ) }}
  apiGroup: rbac.authorization.k8s.io