apiVersion: v1
kind: Service
metadata:
  name: {{ include "probe-from-node.fullname" . }}
  labels:
    {{- include "probe-from-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "probe-from-node.name" . }}