apiVersion: v1
kind: Service
metadata:
  {{- include "common.metadata" (list $ (dict "labelsPath" "service.labels" "annotationsPath" "service.annotations")) | nindent 2 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "object.name" ( list $ "") }}