apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeping.fullname" . }}-exporter
  labels:
    {{- include "kubeping.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.exporter.config | indent 4 }}