---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeping.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubeping.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeping.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "kubeping.fullname" . }}
  apiGroup: rbac.authorization.k8s.io