name: Release

on:
  workflow_dispatch:
    inputs:
      release-name:
        type: string
        description: Release name
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push exporter
        uses: docker/build-push-action@v5
        with:
          context: ./exporter
          file: ./exporter/Dockerfile
          push: true
          tags: ${{ github.repository }}-exporter:${{ inputs.release-name }}, ${{ github.repository }}-exporter:latest

      - name: Build and push web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ${{ github.repository }}-web:${{ inputs.release-name }}, ${{ github.repository }}-web:latest
  
      - name: Package Helm chart
        run: |
          helm package ./helm --destination ./helm-packaged

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ inputs.release-name }}
          tag: ${{ inputs.release-name }}
          bodyFile: "CHANGELOG.md"
          artifacts: "./helm-packaged/*.tgz"
          allowUpdates: true
          artifactErrorsFailBuild: true
          makeLatest: true
